#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user:
    path: /user
    controller: App\Controller\UserController::index

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]

# Rutas del controlador video

new_video:
    path: /video/new
    controller: App\Controller\VideoController::new
    methods: [POST]

video_list:
    path: /video/list
    controller: App\Controller\VideoController::list
    methods: [GET]

video_detail:
    path: /video/detail/{id}
    controller: App\Controller\VideoController::detail
    methods: [GET]
